spring.shell.command.history.enabled: false
keycloak:
  openid_auth_server: http://keycloak.local:8080/auth/realms/dina/protocol/openid-connect/token
  client_id: objectstore
  username: cnc-cm
  password: cnc-cm
elasticsearch:
  server_address: ${ELASTICSEARCH_URL:localhost}
  protocol: http
  port_1: 9200
  port_2: 9300
  indexName: dina_document_index
rabbitmq:
  queue: dina.search.queue
  exchange: dina.search.exchange
  routingkey: dina.search.routingkey
  username: guest
  password: guest
  host: ${RABBITMQ_HOSTNAME:localhost}
  port: 15672
messaging:
  isConsumer: ${IS_MESSAGE_CONSUMER:false}
  isProducer: ${IS_MESSAGE_PRODUCER:false}