spring:
  main:
    web-application-type: none
  shell.command.history.enabled: false
  rabbitmq.listener.simple.default-requeue-rejected: false
keycloak:
  openid_auth_server: http://keycloak.local:8080/auth/realms/dina/protocol/openid-connect/token
  client_id: objectstore
  username: cnc-cm
  password: cnc-cm
elasticsearch:
  server_address: ${ELASTICSEARCH_URL:localhost}
  protocol: https
  port_1: 9200
  port_2: 9300
  username: elastic
  password: changeme
  socketTimeout: 10000
  connectionTimeout: 60000
rabbitmq:
  queue: dina.search.queue
  exchange: dina.search.exchange
  routingkey: dina.search.routingkey
  username: guest
  password: guest
  host: ${RABBITMQ_HOSTNAME:localhost}
  port: 15672
messaging:
  isConsumer: ${IS_MESSAGE_CONSUMER:false}
  isProducer: ${IS_MESSAGE_PRODUCER:false}
