spring.shell.command.history.enabled: false
keycloak:
  openid_auth_server: http://keycloak.local:8080/auth/realms/dina/protocol/openid-connect/token
  client_id: objectstore
  username: cnc-cm
  password: cnc-cm
elasticsearch:
  server_address: elasticsearch-dina
  protocol: http
  port_1: 9200
  port_2: 9300
  indexName: dina_document_index