version: "3.7"

services:

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch-dina:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch-dina
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  elastic-configurator:
      image:  ubuntu2004curl
      command: /code/scripts/wait-for-elasticsearch.sh http://localhost:9200 echo Yves
      volumes:
        - .:/code
      links:
          - elasticsearch-dina:elasticsearch-dina

  # search-cli:
  #   image: my-search-cli:latest
  #   # aafcbicoe/dina-search-cli:0.1
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     default:

volumes:
  elasticsearch-data:
    driver: local      