server:
  port: 8085
elasticsearch:
  host: elasticsearch-dina
  port_1: 9200
  port_2: 9300
  protocol: https
  username: elastic
  password: changeme
  socketTimeout: 10000
  connectionTimeout: 60000
keycloak:
  enabled: false
  realm: dina
  auth-server-url: http://${KEYCLOAK_HOST_IP}:8080/auth
  ssl-required: none
  resource: agent
  public-client: true
  bearer-only: true
  principal-attribute: preferred_username
  # All endpoints require a logged-in user with the "user" role.
  security-constraints:
    - auth-roles:
      - user
      security-collections:
        - patterns:
          - /*
