spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-server/auth/realms/your-realm
server:
  port: 8085
elasticsearch:
  host: elasticsearch-dina
  port: 9200
keycloak:
  enabled: false
