on:
  workflow_dispatch:
    inputs:
      versionTag:
        description: 'Version tag'
        required: true
        default: '0.1'
jobs:
  push:
    name: Build Docker Image and Push to DockerHub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build es-init-container Image and Push
        uses: docker/build-push-action@v3
        with:
          context: es-init-container/.
          push: true
          tags: aafcbicoe/es-init-container:${{ github.event.inputs.versionTag }}
          provenance: false
          
